---
extends: default

rules:
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1

  comments-indentation: disable
  document-start: disable
  document-end: disable
  empty-values: disable

  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0

  new-lines: disable

  key-duplicates: enable
  trailing-spaces: enable
  new-line-at-end-of-file: enable
